### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by hexan86** [RealEnder/dwpa#44]
Specs:
Hp OMEN 
CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz 2.81 GHz 
RAM: 16Gb
64bit Windows 10

Graphic Card: 
Nvidia GeForce GTX 1050 Ti
GPU: Pascal
CUDA Cores: 768
Frame Buffer: 4Gb GDDR5 128-bit
Memory Clock: 7 Gbps
Processor Clock: 1392MHz

Software:
Python: 3.7
Dwpa - Latest from github

When I launch "help_crack.py" this is what happens:
`Challenge cracker for correct results`
`Insufficient memory available`
`hashcat hashcat32.exe died with code 3221225477`
`Check you have OpenCL support`

The system is 64bit and hashcat64.exe works fine, when I use it for my tasks. I don't know why dwpa is opening the 32bit version. I've checked and my Graphic Card supports OpenCL.

There is something that I'm missing? 
Thank you

**Comment by RealEnder** [comment]
For the original problem, you've installed python 32 bit version and since this is checked in python, it looks for 32bit binary of hashcat.
For `nvmlDeviceGetFanSpeed(): Not Supported` part, you should be getting those in normal run of hashcat. Not sure if it's able to control fans under windows or if it requires some additional tuning. This should not be a big issue, since GPU driver will autotune fans. Of course, keep an eye on gpus for this.

**Comment by hexan86** [comment]
Count it as solved issue

**Comment by fourtwizzy** [comment]
If you are finding this in 2023 and hopefully a bit beyond, I had the same error as above. If you are downloading the hashcat binaries going WTF I don't see hashcat64.exe, well have no fear. Instead of using the latest version of hashcat, download and extract [Hashcat v6.2.3](https://github.com/hashcat/hashcat/releases/tag/v6.2.3) instead. Put the python script you are attempting to run in the root folder (the one where you see hashcat.exe [for the beginners]). Then use the command prompt to navigate to that folder. Enter "python yourscript.py", and you should be good to go. At least it did for me on Windows 10 using a 2080Ti as of today. In particular I received this error message while attempting to run the [wpa-sec](https://wpa-sec.stanev.org/?) help-crack.py.
